name: Latest YouTube Videos
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in latest videos from YouTube
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCTNFKRALTZoSQS6mDOuDs2Q"
          max_post_count: 6
          template: '<a href="$url"><img src="https://img.youtube.com/vi/$video_id/mqdefault.jpg" alt="$title" width="300"/></a><br/>**[$title]($url)**<br/>📅 $date<br/><br/>'
          date_format: "dd MMM yyyy" 