name: Latest YouTube Videos
on:
  schedule:
    # Uruchom codziennie o 8:00 UTC
    - cron: '0 8 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in latest videos from YouTube
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCTNFKRALTZoSQS6mDOuDs2Q"
          max_post_count: 6
          template: '<div align="center"><a href="$url"><img src="https://img.youtube.com/vi/##YOUTUBE_ID##/hqdefault.jpg" width="400" alt="$title" style="border-radius: 10px; box-shadow: 0 4px 8px rgba(0,0,0,0.2);"/></a><br/><strong style="font-size: 14px;">$title</strong></div>'
          date_format: "dd MMM yyyy"
          filter_comments: "true"
          reddit_preview_image: "false"
          custom_tags: "##YOUTUBE_ID##,(?:youtube\\.com\\/(?:[^\\/]+\\/.+\\/|(?:v|e(?:mbed)?)\\/|.*[?&]v=)|youtu\\.be\\/)([^&\\n?#]+)" 