name: Latest YouTube Videos
on:
  schedule:
    # Uruchom codziennie o 8:00 UTC
    - cron: '0 8 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in latest videos from YouTube
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCTNFKRALTZoSQS6mDOuDs2Q"
          max_post_count: 6
          template: "[![$title](https://img.youtube.com/vi/##YOUTUBE_ID##/mqdefault.jpg)]($url)"
          date_format: "dd MMM yyyy"
          filter_comments: "true"
          reddit_preview_image: "false"
          custom_tags: "##YOUTUBE_ID##,(?:youtube\\.com\\/(?:[^\\/]+\\/.+\\/|(?:v|e(?:mbed)?)\\/|.*[?&]v=)|youtu\\.be\\/)([^&\\n?#]+)" 